# Generated by Django 4.2.7 on 2026-03-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=500, verbose_name='Original link')),
                ('short_code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Shortcut')),
                ('clicks', models.IntegerField(default=0, verbose_name='Redirects')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
            options={
                'verbose_name': 'Shortcut',
                'verbose_name_plural': 'Shortcuts',
                'ordering': ['-created_at'],
            },
        ),
    ]
